# Should be automatically switched (see https://github.com/Johardt/dotfiles/issues/7)
theme = "catppuccin_latte"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"